# Generated by Django 3.2.9 on 2021-11-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20211128_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='color',
            new_name='hexcolor',
        ),
    ]
